{% set name = "page" %}
{% set version = "4.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/I60R/page/archive/v{{ version }}.tar.gz
  sha256: 51cf01933180499b27027fcdbda067f0cf80cebaa06d62400b655419f1806d46

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - page --help

about:
  home: https://github.com/I60R/page
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Use Neovim as pager
  dev_url: https://github.com/I60R/page

extra:
  recipe-maintainers:
    - danielnachun
