context:
  version: 4.6.3

package:
  name: page
  version: ${{ version }}

source:
  url: https://github.com/I60R/page/archive/v${{ version }}.tar.gz
  sha256: 51cf01933180499b27027fcdbda067f0cf80cebaa06d62400b655419f1806d46

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - page --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Use Neovim as pager
  homepage: https://github.com/I60R/page
  repository: https://github.com/I60R/page

extra:
  recipe-maintainers:
    - danielnachun
